---
- name: Restart docker
  systemd:
    name: docker
    daemon_reload: true
    state: "{{ 'reloaded' if docker_systemd_reload | bool else 'restarted' }}"
    masked: false
  become: true

- name: Restart containerd
  service:
    name: containerd
    state: restarted
  become: true
