---
create_kolla_user: false

kolla_user: "kolla"
kolla_group: "kolla"

change_selinux: true

selinux_state: "permissive"

# If true, the host firewall service (firewalld or ufw) will be disabled.
disable_firewall: true

git_http_proxy: ""
git_https_proxy: ""

node_config_directory: "/etc/kolla"

container_engine: "{{ kolla_container_engine | default('docker') }}"
