---
- project:
    queue: kolla
    templates:
      - ansible-role-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - kolla-ansible-debian
        - kolla-ansible-debian-podman
        - kolla-ansible-ubuntu
        - kolla-ansible-ubuntu-podman
        - kayobe-overcloud-rocky9:
            voting: false
        - kayobe-overcloud-host-configure-rocky9
        - kayobe-overcloud-host-configure-ubuntu-noble
        - kayobe-overcloud-ubuntu-noble
        - kayobe-overcloud-ubuntu-noble-podman
    check-arm64:
      jobs:
        - kolla-ansible-debian-aarch64
        - kolla-ansible-debian-aarch64-podman
    gate:
      jobs:
        - kolla-ansible-debian
        - kolla-ansible-debian-podman
        - kolla-ansible-ubuntu
        - kolla-ansible-ubuntu-podman
        - kayobe-overcloud-host-configure-rocky9
        - kayobe-overcloud-host-configure-ubuntu-noble
        - kayobe-overcloud-ubuntu-noble
        - kayobe-overcloud-ubuntu-noble-podman
