---
- project:
    queue: kolla
    templates:
      - ansible-role-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - kolla-ansible-debian-trixie:
            files: &ack_files
              - roles/
        - kolla-ansible-debian-trixie-podman:
            files: *ack_files
        - kolla-ansible-debian-bookworm-upgrade:
            files: *ack_files
        - kolla-ansible-rocky-10:
            files: *ack_files
        - kolla-ansible-rocky-10-upgrade:
            files: *ack_files
        - kolla-ansible-rocky-10-podman:
            files: *ack_files
        - kolla-ansible-ubuntu-noble:
            files: *ack_files
        - kolla-ansible-ubuntu-noble-podman:
            files: *ack_files
        - kolla-ansible-ubuntu-noble-upgrade:
            files: *ack_files
        - kayobe-overcloud-host-configure-rocky10:
            files: *ack_files
        - kayobe-overcloud-host-configure-ubuntu-noble:
            files: *ack_files
        - kayobe-overcloud-rocky10:
            files: *ack_files
        - kayobe-overcloud-rocky10-podman:
            files: *ack_files
        - kayobe-overcloud-ubuntu-noble:
            files: *ack_files
        - kayobe-overcloud-ubuntu-noble-podman:
            files: *ack_files
    check-arm64:
      jobs:
        - kolla-ansible-debian-trixie-aarch64:
            files: *ack_files
        - kolla-ansible-debian-trixie-aarch64-podman:
            files: *ack_files
        - kolla-ansible-debian-bookworm-aarch64-upgrade:
            files: *ack_files
    gate:
      jobs:
        - kolla-ansible-debian-trixie:
            files: *ack_files
        - kolla-ansible-debian-trixie-podman:
            files: *ack_files
        - kolla-ansible-debian-bookworm-upgrade:
            files: *ack_files
        - kolla-ansible-rocky-10:
            files: *ack_files
        - kolla-ansible-rocky-10-upgrade:
            files: *ack_files
        - kolla-ansible-rocky-10-podman:
            files: *ack_files
        - kolla-ansible-ubuntu-noble:
            files: *ack_files
        - kolla-ansible-ubuntu-noble-podman:
            files: *ack_files
        - kolla-ansible-ubuntu-noble-upgrade:
            files: *ack_files
        - kayobe-overcloud-host-configure-rocky10:
            files: *ack_files
        - kayobe-overcloud-host-configure-ubuntu-noble:
            files: *ack_files
        - kayobe-overcloud-rocky10:
            files: *ack_files
        - kayobe-overcloud-rocky10-podman:
            files: *ack_files
        - kayobe-overcloud-ubuntu-noble:
            files: *ack_files
        - kayobe-overcloud-ubuntu-noble-podman:
            files: *ack_files
